name: CD-Dev

permissions:
  contents: read
  packages: read
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull image
        run: docker pull ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/aspwebproject:latest

      - name: Run container
        run: |
          docker run -d -p 8080:80 \
            -e GROK_KEY=${{ secrets.GROK_KEY }} \
            ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/aspwebproject:latest

      - name: Verify container
        run: |
          sleep 5
          docker ps
    
    
