name: CD-Dev

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Pull image
        run: docker pull ghcr.io/yunusemretuncer/aspwebproject:latest

      - name: Run container
        run: |
          docker run -d -p 8080:80 \
            -e GROK_KEY=${{ secrets.GROK_KEY }} \
            ghcr.io/yunusemretuncer/aspwebproject:latest

      - name: Verify container
        run: |
          sleep 5
          docker ps
    
    
